PIXEL_TO_CM_RATIO = 2;

WHEEL_RADIUS_IN_CM = 2.1; # in Cm (diameter is 42 mm)

WHEEL_RADIUS_IN_PX = WHEEL_RADIUS_IN_CM / PIXEL_TO_CM_RATIO;

WHEEL_BASE_LENGTH_IN_CM = 8.85;

WHEEL_BASE_LENGTH_IN_PX = WHEEL_BASE_LENGTH_IN_CM / PIXEL_TO_CM_RATIO;

MAX_TRANSLATIONAL_VELOCITY = 0.813; # in m/s
